# https://taskfile.dev
version: '3'

tasks:
  test:
    env:
      RUST_BACKTRACE: full
    cmds:
      - cargo test --verbose
      - cargo run --example usage
  lint:
    cmds:
      - pre-commit run --all
  render:
    cmds:
      - gomplate -f README.md.tpl -o README.md
